sudo: required

services:
    - docker

before_install:
    - docker build -t uka/travis -f Dockerfile.dev .
#test commit
script:
    - docker run -e CI=true uka/travis npm run test -- --watchAll=false

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-usej"
    env: "dockerusej-env"
    bucket_name: "elasticbeanstalk-eu-central-1-196658334701"
    bucket_path: "docker-usej"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secrect_access_key:
        secure: "$AWS_SECRECT_KEY"
