sudo: required

services:
    - docker

before_install:
    - docker build -t uka/travis -f Dockerfile.dev .
#test commit
script:
    - docker run -e CI=true uka/travis npm run test -- --watchAll=false


