sudo: required
install: travis_wait 30 mvn install

services:
    - docker

before_install:
    - docker build -t uka/travis -f Dockerfile.dev .
#test commit
script:
    - docker run uka/travis npm run test -- --coverage


